### ISSUE TITLE
"rage" ability from barbarian class doesn't work.

### ISSUE THREAD

**Issue by ilore** [irbian/foundryvtt-D35E-lang-es-es#49]
As the title says, the "rage" ability from the barbarian class doesn't work when you use the spanish translation module. If you create a barbarian using the english version of the system, "rage" works fine.

**Comment by ilore** [comment]
I have discovered what's happening: If you edit Rage and go to Configuration/details/Special actions (advanced)/Action , you will read this:

Create unique Enraged from D35E.commonbuffs on self; Set buff Enraged field data.level to 1 on self;Activate buff Enraged on self

The system searches "Enraged" in the compendium, but it doesn't exist anymore because it has been translated. If you write this, the ability works fine again:

Create unique "Furioso (Enraged)" from D35E.commonbuffs on self; Set buff "Furioso (Enraged)" field data.level to 1 on self;Activate buff "Furioso (Enraged)" on self

**Comment by irbian** [comment]
Added more info on 35e tracker https://gitlab.com/dragonshorn/D35E/-/issues/774

**Comment by irbian** [comment]
Will be solved when https://gitlab.com/dragonshorn/D35E/-/merge_requests/897 is merged

**Comment by irbian** [comment]
Looks solved on 0.99.10
