### ISSUE TITLE
All "composite bows" translations are broken

### ISSUE THREAD

**Issue by ilore** [irbian/foundryvtt-D35E-lang-es-es#52]
All composite bows are translated to spanish. However, in the system compendium, all composite bows show the same error. For example, the composite longbow +1 shows this name:

undefined (Composite longbow (+1))

**Comment by irbian** [comment]
duplicated on https://github.com/irbian/foundryvtt-D35E-lang-es-es/issues/55

**Comment by irbian** [comment]
Wasn´t the same error, the composite bows where different items. They have been added and translated and will appear soon

**Comment by irbian** [comment]
Must be solved on 0.16.2
