### ISSUE TITLE
La habilidad de bardo "inspire courage" ya no funciona.

### ISSUE THREAD

**Issue by ilore** [irbian/foundryvtt-D35E-lang-es-es#54]
Tras la última actualización del sistema (la 0.98.4) el buff "inspire courage" de la habilidad del bardo "música de bardo" ha dejado de funcionar al usar el módulo de traducción.

![Consola](https://user-images.githubusercontent.com/32924279/146935078-1b7c2f3d-7afc-4767-8286-ae9910de6418.jpg)

**Comment by irbian** [comment]
It´s babele version updated?

**Comment by ilore** [comment]
> It´s babele version updated?

When I detected the problem, I was using FVTT 0.8.9;  3.5eSRD 0.98.5; 3.5 SRD translation - Spanish 0.16.1 and Babele 2.1.3. But, I have updated everything (FVTT to V9 and the modules to V9) and the problem persists.

**Comment by ilore** [comment]
I have tried to create a weapon with the same function as "bardic music": create and activate the "inspire courage" buff on target. the console shows the same error:

![problem](https://user-images.githubusercontent.com/32924279/147493162-4fa562c6-ebc4-4480-9093-84008f655a64.jpg)

**Comment by irbian** [comment]
He actualizado todo a la ultima versión y no puedo reproducirlo ¿te sigue pasando?

**Comment by ilore** [comment]
> He actualizado todo a la ultima versión y no puedo reproducirlo ¿te sigue pasando?

Si, es más: ahora si intento crear un bardo, aunque busque la clase traducida, la pone en inglés y entonces, al no encontrar las características de clase en inglés, no funciona nada.

**Comment by irbian** [comment]
Must be resolved when https://gitlab.com/dragonshorn/D35E/-/merge_requests/897 is merged

**Comment by irbian** [comment]
Looks like its already solved on 0.99.10, try again (and make sure you have at least one point of perform)
