### ISSUE TITLE
[Bug] Dotes con fórmula no son traducidas con lo que quedan como undefined

### ISSUE THREAD

**Issue by DavidAremaCarretero** [irbian/foundryvtt-D35E-lang-es-es#55]
![image](https://user-images.githubusercontent.com/1208628/152694503-66b050ec-a02d-4784-8ccd-994cff3fc5df.png)
En dotes las cuales dependen de una selección, su literal no es traducido con lo que en vez de darse el fallback de quedar el literal original en inglés, quedan como _undefined_.

**Comment by irbian** [comment]
Must be solved on 0.16.2
